name: ctype
favicon: null
layout_spectrum: 0.49553
typography_spectrum: 0.7459
title: c.type
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#159f9f'
    - '#ffffff'
    - '#faf101'
    - '#98d5d5'
    - '#77bebe'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
