name: ctype
favicon: null
layout_spectrum: 0.74441
typography_spectrum: 0.50912
title: c.type
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1d1d1'
    - '#afafaf'
    - '#797979'
    - '#090909'
    - '#434343'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
