name: ctype
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.50596
title: c.type
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bae3e3'
    - '#4bb7b7'
    - '#ffffff'
    - '#89d0d0'
    - '#222222'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
