name: ctype
favicon: null
layout_spectrum: 0.51937
typography_spectrum: 0.25559
title: c.type
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#009999'
    - '#ffffff'
    - '#4bb7b7'
    - '#bae3e3'
    - '#89d0d0'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
