name: ctype
favicon: null
layout_spectrum: 0.74143
typography_spectrum: 0.24161
title: c.type
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#149e9e'
    - '#ffffff'
    - '#7ac7c7'
    - '#8a9c9c'
    - '#56e2f3'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
